package io.tarrie.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import io.tarrie.database.contants.DbAttributes;
import io.tarrie.database.contants.DbConstants;

import java.util.Date;

@DynamoDBTable(tableName = DbConstants.BASE_TABLE)
public class Invite {
  private String entityId;
  private String invitedId;
  private Date createdTime;

  @DynamoDBHashKey(attributeName = DbAttributes.HASH_KEY)
  public String getEntityId() {
    return entityId;
  }

  @DynamoDBRangeKey(attributeName = DbAttributes.SORT_KEY)
  public String getInvitedId() {
    return invitedId;
  }

  @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
  @DynamoDBAttribute(attributeName = DbAttributes.DATA)
  public Date getCreatedTime() {
    return createdTime;
  }

  public void setCreatedTime(Date createdTime) {
    this.createdTime = createdTime;
  }

  public void setEntityId(String entityId) {
    this.entityId = entityId;
  }

  public void setInvitedId(String invitedId) {
    this.invitedId = invitedId;
  }
}
