package io.tarrie.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedDefault;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.tarrie.model.constants.CharacterLimit;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@DynamoDBDocument
@ApiModel(description="The location of a Tarrie entity. Its OK if this object is empty because the event could be virtual")
public class Location {
    public String state;
    public String city;
    public int zipCode;
    public String line1;
    public String line2;
    public String locName;
    public float latitude;
    public float longitude;

    @ApiModelProperty(notes="The latitude of the location", example="34.055560")
    @DynamoDBAttribute
    public float getLatitude() {
        return latitude;
    }

    @ApiModelProperty(notes="The longitude of the location", example="-117.182600", position=5)
    @DynamoDBAttribute
    public float getLongitude() {
        return longitude;
    }

    @ApiModelProperty(notes = "The zipcode of location ", example = "92373")
    @DynamoDBAttribute
    public int getZipCode() {
        return zipCode;
    }

    @ApiModelProperty(notes = "The city  location ", example = "Redlands")
    @NotNull
    @DynamoDBAttribute
    public String getCity() {
        return city;
    }

    @ApiModelProperty(notes = "Line 1 of a standard street address form", example = "1623 W Columbia Ave")
    @DynamoDBAttribute
    public String getLine1() {
        return line1;
    }

    @ApiModelProperty(notes = "Line 2 of a standard street address form", example = "APT 2")
    @DynamoDBAttribute
    public String getLine2() {
        return line2;
    }

    @NotNull
    @Size(min=0, max= CharacterLimit.SMALL)
    @ApiModelProperty(notes="The location name", example="Bogo Party House")
    @DynamoDBAttribute
    public String getLocName() {
        return locName;
    }

    @ApiModelProperty(notes = "The state of the location ", example = "CA")
    @NotNull
    @DynamoDBAttribute
    public String getState() {
        return state;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public void setLatitude(float latitude) {
        this.latitude = latitude;
    }

    public void setLine1(String line1) {
        this.line1 = line1;
    }

    public void setLine2(String line2) {
        this.line2 = line2;
    }

    public void setLocName(String locName) {
        this.locName = locName;
    }

    public void setLongitude(float longitude) {
        this.longitude = longitude;
    }

    public void setState(String state) {
        this.state = state;
    }

    public void setZipCode(int zipCode) {
        this.zipCode = zipCode;
    }
}
