package io.tarrie.model.messages;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import io.tarrie.database.contants.DbAttributes;
import io.tarrie.database.contants.DbConstants;

import javax.validation.constraints.NotNull;
import java.util.Date;

@DynamoDBTable(tableName = DbConstants.BASE_TABLE)
public class EntityInvited {

  private String id;
  private String invitedId;
  private Date createdTime;

  @DynamoDBHashKey(attributeName = DbAttributes.HASH_KEY)
  @NotNull
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  @DynamoDBRangeKey(attributeName = DbAttributes.SORT_KEY)
  @NotNull
  public String getInvitedId() {
    return invitedId;
  }

  public void setInvitedId(String invitedId) {
    this.invitedId = invitedId;
  }

  @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
  @DynamoDBAttribute(attributeName = DbAttributes.DATA)
    public Date getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
}
